# Generated by Django 3.0.3 on 2020-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brief', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('brief', models.CharField(max_length=150)),
                ('other_info', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=150)),
                ('actors', models.ManyToManyField(to='engine.Actor')),
            ],
        ),
    ]
