# Generated by Django 3.0.3 on 2020-09-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20200907_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='collaborate',
            field=models.ManyToManyField(related_name='_actor_collaborate_+', to='engine.Actor'),
        ),
    ]
